# Generated by Django 5.2 on 2025-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=50)),
                ('model_size_label', models.CharField(max_length=50)),
                ('precision', models.CharField(max_length=50)),
                ('model_size', models.FloatField()),
                ('layers', models.IntegerField()),
                ('parameters_m', models.FloatField()),
                ('flops_b', models.FloatField()),
                ('fps_gpu', models.FloatField()),
                ('avg_emissions_gco2eq', models.FloatField()),
                ('avg_energy_mwh', models.FloatField()),
                ('map_50', models.FloatField()),
                ('map_50_95', models.FloatField()),
                ('training_time', models.FloatField()),
                ('creator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'v_model_energy_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('final_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('latency_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('execution_time_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('energy_consumption_mwh', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('emissions_gco2eq', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('fps_gpu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('map_50', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('map_50_95', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FullDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=50)),
                ('model_size_label', models.CharField(max_length=50)),
                ('precision', models.CharField(max_length=50)),
                ('layers', models.IntegerField()),
                ('parameters_m', models.FloatField()),
                ('flops_b', models.FloatField()),
                ('model_size', models.FloatField()),
                ('training_time', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('accuracy', models.FloatField()),
                ('final_loss', models.FloatField()),
                ('latency_ms', models.FloatField()),
                ('fps_gpu', models.FloatField()),
                ('avg_emissions_gco2eq', models.FloatField()),
                ('avg_energy_mwh', models.FloatField()),
                ('map_50', models.FloatField()),
                ('map_50_95', models.FloatField()),
                ('creator', models.CharField(max_length=100)),
                ('cpu_type', models.CharField(max_length=250)),
                ('memory_gpu', models.IntegerField()),
                ('memory_gb', models.IntegerField()),
                ('cpu_frequency_ghz', models.FloatField()),
                ('max_power_watts', models.IntegerField()),
            ],
            options={
                'db_table': 'v_model_full_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDistillation',
            fields=[
                ('knowledged_distillation_id', models.AutoField(primary_key=True, serialize=False)),
                ('softmax_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('loss_function', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'knowledge_distillation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('architecture', models.CharField(blank=True, max_length=100, null=True)),
                ('parameter_count', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('layer_count', models.IntegerField(blank=True, null=True)),
                ('model_size_label', models.CharField(blank=True, max_length=1, null=True)),
                ('flops_billion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('model_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelOptimization',
            fields=[
                ('model_optimization_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'model_optimization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('model_task_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'model_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('optimization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('optimization_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'optimization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precision',
            fields=[
                ('precision_id', models.AutoField(primary_key=True, serialize=False)),
                ('precision_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'precision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pruning',
            fields=[
                ('pruning_id', models.AutoField(primary_key=True, serialize=False)),
                ('pruning_strategie', models.CharField(blank=True, max_length=50, null=True)),
                ('pruning_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pruning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantization',
            fields=[
                ('quantization_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantization_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_precision', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'quantization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_type', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_gpu', models.IntegerField(blank=True, null=True)),
                ('memory_gb', models.IntegerField(blank=True, null=True)),
                ('cpu_frequency_ghz', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_power_watts', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
