# Generated by Django 5.2 on 2025-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=50)),
                ('parameters_m', models.FloatField()),
                ('layers', models.IntegerField()),
                ('model_size_label', models.CharField(max_length=50)),
                ('flops_b', models.FloatField()),
                ('model_size', models.FloatField()),
                ('training_time', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('precision', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('fps_gpu', models.FloatField()),
                ('avg_emissions_gco2eq', models.FloatField()),
                ('avg_energy_mwh', models.FloatField()),
                ('map_50', models.FloatField()),
                ('map_50_95', models.FloatField()),
            ],
            options={
                'db_table': 'v_simplify_data_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('final_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('latency_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('execution_time_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('energy_consumption_mwh', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('emissions_gco2eq', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('fps_gpu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('map_50', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('map_50_95', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evaluation_date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationView',
            fields=[
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_memory', models.IntegerField(blank=True, null=True)),
                ('computer_ram', models.IntegerField(blank=True, null=True)),
                ('cpu_frenquency', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accuracy', models.FloatField()),
                ('final_loss', models.FloatField()),
                ('latency_ms', models.FloatField()),
                ('execution_time_ms', models.FloatField()),
                ('energy_consumption_mwh', models.FloatField()),
                ('emissions_gco2eq', models.FloatField()),
                ('fps_gpu', models.FloatField()),
                ('map_50', models.FloatField()),
                ('map_50_95', models.FloatField()),
                ('date', models.DateTimeField()),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'v_evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FullDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=50)),
                ('parameters_m', models.FloatField()),
                ('layers', models.IntegerField()),
                ('model_size_label', models.CharField(max_length=50)),
                ('flops_b', models.FloatField()),
                ('model_size', models.FloatField()),
                ('training_time', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('precision', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('creator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'v_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDistillation',
            fields=[
                ('knowledged_distillation_id', models.AutoField(primary_key=True, serialize=False)),
                ('softmax_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('loss_function', models.CharField(blank=True, max_length=50, null=True)),
                ('knowledged_distillation_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'knowledge_distillation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDistillationView',
            fields=[
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_memory', models.IntegerField(blank=True, null=True)),
                ('computer_ram', models.IntegerField(blank=True, null=True)),
                ('cpu_frenquency', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('softmax_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('loss_function', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('optimization_id', models.IntegerField()),
                ('optimization_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_knowledge_distillation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('architecture', models.CharField(blank=True, max_length=100, null=True)),
                ('parameter_count', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('layer_count', models.IntegerField(blank=True, null=True)),
                ('model_size_label', models.CharField(blank=True, max_length=1, null=True)),
                ('flops_billion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('model_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('model_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelOptimization',
            fields=[
                ('model_optimization_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'model_optimization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelOptimizationView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('optimization_id', models.IntegerField()),
                ('optimization_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'v_model_optimization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('model_task_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'model_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTaskView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'v_model_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=50)),
                ('parameters_m', models.FloatField()),
                ('layers', models.IntegerField()),
                ('model_size_label', models.CharField(max_length=50)),
                ('flops_b', models.FloatField()),
                ('model_size', models.FloatField()),
                ('training_time', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('precision', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('creator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'v_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('optimization_id', models.AutoField(primary_key=True, serialize=False)),
                ('optimization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('optimization_date', models.DateTimeField(blank=True, null=True)),
                ('optimization_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'optimization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptimizationView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_memory', models.IntegerField(blank=True, null=True)),
                ('computer_ram', models.IntegerField(blank=True, null=True)),
                ('cpu_frenquency', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_optimization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precision',
            fields=[
                ('precision_id', models.AutoField(primary_key=True, serialize=False)),
                ('precision_name', models.CharField(blank=True, max_length=50, null=True)),
                ('precision_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'precision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecisionView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'v_precision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pruning',
            fields=[
                ('pruning_id', models.AutoField(primary_key=True, serialize=False)),
                ('pruning_strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('pruning_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('pruning_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pruning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PruningView',
            fields=[
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_memory', models.IntegerField(blank=True, null=True)),
                ('computer_ram', models.IntegerField(blank=True, null=True)),
                ('cpu_frenquency', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('optimization_id', models.IntegerField()),
                ('optimization_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_pruning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantization',
            fields=[
                ('quantization_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantization_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantization_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'quantization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuantizationView',
            fields=[
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_memory', models.IntegerField(blank=True, null=True)),
                ('computer_ram', models.IntegerField(blank=True, null=True)),
                ('cpu_frenquency', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_precision', models.CharField(blank=True, max_length=50, null=True)),
                ('optimization_id', models.IntegerField()),
                ('optimization_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_quantization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_type', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_gpu', models.IntegerField(blank=True, null=True)),
                ('memory_gb', models.IntegerField(blank=True, null=True)),
                ('cpu_frequency_ghz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_power_watts', models.IntegerField(blank=True, null=True)),
                ('resource_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_memory', models.IntegerField(blank=True, null=True)),
                ('computer_ram', models.IntegerField(blank=True, null=True)),
                ('cpu_frenquency', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_watts', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'v_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=50, null=True)),
                ('task_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'v_task',
                'managed': False,
            },
        ),
    ]
